---
name: WWW-YahooJapan-KanaAddress
version: v0.1.0
author:
  - 'Masahiro Honma <hiratara@cpan.org>'
abstract: translating the address in Japan into kana.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP::UserAgent: 0
  Test::More: 0
  version: 0
provides:
  WWW::YahooJapan::KanaAddress:
    file: lib/WWW/YahooJapan/KanaAddress.pm
    version: v0.1.0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
